import React, { useState, useEffect } from 'react';
import {
  Sparkles,
  BarChart3,
  Calendar,
  Layers,
  FileText,
  AlertCircle,
  Loader2,
  CheckSquare,
  Square,
  Download,
  BookOpen,
  ArrowRight
} from 'lucide-react';
import {
  BarChart,
  Bar,
  XAxis,
  YAxis,
  Tooltip,
  ResponsiveContainer,
  CartesianGrid
} from 'recharts';
import { api } from '../services/api';
import {
  InsightsResponse,
  DocumentItem,
  MultiPaperSummarizeResponse
} from '../types';

export const InsightsPage: React.FC = () => {
  const [data, setData] = useState<InsightsResponse | null>(null);
  const [loading, setLoading] = useState(true);
  const [documents, setDocuments] = useState<DocumentItem[]>([]);
  const [selectedDocIds, setSelectedDocIds] = useState<string[]>([]);
  const [summaryData, setSummaryData] = useState<MultiPaperSummarizeResponse | null>(null);
  const [summarizing, setSummarizing] = useState(false);

  useEffect(() => {
    loadData();
  }, []);

  const loadData = async () => {
    try {
      setLoading(true);
      const [insights, docsRes] = await Promise.all([
        api.getInsights(),
        api.getDocuments({ limit: 100 })
      ]);
      setData(insights);
      const docs = docsRes.items || [];
      setDocuments(docs);
      if (docs.length > 0) {
        setSelectedDocIds(docs.slice(0, Math.min(3, docs.length)).map((d) => d.id));
      }
    } catch (e) {
      console.error(e);
    } finally {
      setLoading(false);
    }
  };

  const handleToggleDoc = (id: string) => {
    if (selectedDocIds.includes(id)) {
      setSelectedDocIds(selectedDocIds.filter((d) => d !== id));
    } else {
      setSelectedDocIds([...selectedDocIds, id]);
    }
  };

  const handleSelectAll = () => {
    if (selectedDocIds.length === documents.length) {
      setSelectedDocIds([]);
    } else {
      setSelectedDocIds(documents.map((d) => d.id));
    }
  };

  const handleGenerateSummary = async () => {
    if (selectedDocIds.length === 0) return;
    try {
      setSummarizing(true);
      const res = await api.summarizeSelectedPapers(selectedDocIds);
      setSummaryData(res);
    } catch (e) {
      console.error(e);
      alert('Error generating multi-paper summary.');
    } finally {
      setSummarizing(false);
    }
  };

  const handleDownloadSummary = () => {
    if (!summaryData) return;
    const content = `# ${summaryData.synthesis_title}
Generated by ARCHER (Academic Research Intelligence Engine)

## Executive Multi-Document Synthesis
${summaryData.executive_synthesis}

## Key Methodological Takeaways
${summaryData.methodological_takeaways.map((t) => `- ${t}`).join('\n')}

## Joint Empirical Findings
${summaryData.joint_empirical_findings.map((f) => `- ${f}`).join('\n')}

## Individual Paper Summaries
${summaryData.paper_summaries.map((p) => `
### ${p.paper_title}
- Objective: ${p.objective || 'N/A'}
- Methodology: ${p.methodology || 'N/A'}
- Key Findings: ${p.findings || 'N/A'}
- Limitations: ${p.limitations || 'N/A'}
- Summary: ${p.summary || 'N/A'}
`).join('\n')}
`;

    const blob = new Blob([content], { type: 'text/markdown;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.setAttribute('download', `archer_multi_paper_summary_${new Date().toISOString().slice(0, 10)}.md`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  if (loading || !data) {
    return (
      <div className="flex items-center justify-center h-64">
        <Loader2 className="w-8 h-8 text-brand-600 dark:text-brand-400 animate-spin" />
      </div>
    );
  }

  return (
    <div className="max-w-7xl mx-auto space-y-8 pb-12">
      {/* Header */}
      <div>
        <h1 className="text-2xl font-bold text-slate-900 dark:text-white tracking-tight flex items-center gap-2.5">
          <Sparkles className="w-6 h-6 text-brand-600 dark:text-brand-400" />
          <span>Research Analytics & Multi-Paper Summarization</span>
        </h1>
        <p className="text-xs text-slate-500 dark:text-slate-400 mt-1">
          Explore publication timelines, methodology distributions, and synthesize integrated multi-document executive summaries.
        </p>
      </div>

      {/* Multi-Document Summarization Workflow Container */}
      <div className="p-6 rounded-3xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 space-y-6 shadow-xs transition-colors">
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 border-b border-slate-100 dark:border-slate-800 pb-4">
          <div>
            <h2 className="text-base font-bold text-slate-900 dark:text-slate-100 flex items-center gap-2">
              <FileText className="w-5 h-5 text-brand-600 dark:text-brand-400" />
              <span>Multi-Document Executive Summarization</span>
            </h2>
            <p className="text-xs text-slate-500 dark:text-slate-400 mt-0.5">
              Select papers in your library to generate an integrated comparative summary explaining their shared problems, architectures, and findings.
            </p>
          </div>

          <div className="flex items-center gap-2 shrink-0">
            <button
              onClick={handleSelectAll}
              className="px-3 py-1.5 rounded-xl border border-slate-200 dark:border-slate-700 bg-slate-50 dark:bg-slate-800 text-xs font-semibold text-slate-700 dark:text-slate-300 hover:bg-slate-100 dark:hover:bg-slate-700/80 transition-colors"
            >
              {selectedDocIds.length === documents.length ? 'Deselect All' : 'Select All Papers'}
            </button>
            <button
              onClick={handleGenerateSummary}
              disabled={selectedDocIds.length === 0 || summarizing}
              className="px-4 py-2 rounded-xl bg-brand-500 hover:bg-brand-400 text-slate-950 text-xs font-bold shadow-md shadow-brand-500/20 disabled:opacity-50 transition-all flex items-center gap-2"
            >
              {summarizing ? (
                <>
                  <Loader2 className="w-4 h-4 animate-spin" />
                  <span>Synthesizing...</span>
                </>
              ) : (
                <>
                  <Sparkles className="w-4 h-4" />
                  <span>Generate Summary ({selectedDocIds.length})</span>
                </>
              )}
            </button>
          </div>
        </div>

        {/* Paper Selection Checklist */}
        <div className="space-y-2">
          <label className="text-xs font-semibold text-slate-700 dark:text-slate-300">
            Choose Papers for Synthesis:
          </label>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-2.5 max-h-48 overflow-y-auto p-1">
            {documents.map((doc) => {
              const isSelected = selectedDocIds.includes(doc.id);
              return (
                <div
                  key={doc.id}
                  onClick={() => handleToggleDoc(doc.id)}
                  className={`p-2.5 rounded-xl border text-xs cursor-pointer flex items-start gap-2.5 transition-all ${
                    isSelected
                      ? 'border-brand-500 bg-brand-50/70 dark:bg-brand-950/40 text-slate-900 dark:text-slate-100 font-semibold'
                      : 'border-slate-200 dark:border-slate-800 bg-slate-50/50 dark:bg-slate-950/40 text-slate-600 dark:text-slate-300 hover:border-slate-300 dark:hover:border-slate-700'
                  }`}
                >
                  <div className="mt-0.5 text-brand-600 dark:text-brand-400 shrink-0">
                    {isSelected ? <CheckSquare className="w-4 h-4" /> : <Square className="w-4 h-4" />}
                  </div>
                  <span className="truncate flex-1">{doc.title}</span>
                </div>
              );
            })}
          </div>
        </div>

        {/* Summary Output Area */}
        {summaryData && (
          <div className="pt-4 border-t border-slate-100 dark:border-slate-800 space-y-6">
            <div className="flex items-center justify-between">
              <div>
                <h3 className="text-base font-bold text-slate-900 dark:text-slate-100">
                  {summaryData.synthesis_title}
                </h3>
                <span className="text-xs font-mono text-emerald-700 dark:text-emerald-400 font-medium">
                  Synthesized across {summaryData.papers_count} selected papers
                </span>
              </div>
              <button
                onClick={handleDownloadSummary}
                className="inline-flex items-center gap-1.5 px-3.5 py-2 rounded-xl border border-slate-300 dark:border-slate-700 bg-slate-100 dark:bg-slate-800 text-xs font-semibold text-slate-900 dark:text-slate-100 hover:bg-slate-200 dark:hover:bg-slate-700 transition-colors shadow-xs"
              >
                <Download className="w-4 h-4" />
                <span>Download Report</span>
              </button>
            </div>

            {/* Executive Synthesis Solid Dark Card */}
            <div className="p-5 md:p-6 rounded-2xl bg-slate-100 dark:bg-slate-950 border border-slate-200 dark:border-slate-800 space-y-3 shadow-xs">
              <h4 className="text-xs font-bold uppercase tracking-wider text-brand-700 dark:text-brand-400 flex items-center gap-2">
                <BookOpen className="w-4 h-4" />
                <span>Executive Synthesis & Comparative Takeaways</span>
              </h4>
              <p className="text-xs md:text-sm text-slate-800 dark:text-slate-100 leading-relaxed whitespace-pre-line">
                {summaryData.executive_synthesis}
              </p>
            </div>

            {/* Key Findings and Takeaways */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div className="p-5 rounded-2xl bg-slate-100 dark:bg-slate-950 border border-slate-200 dark:border-slate-800 space-y-3 shadow-xs">
                <h4 className="text-xs font-bold text-slate-900 dark:text-slate-100">
                  Methodological Takeaways
                </h4>
                <ul className="space-y-2 text-xs text-slate-700 dark:text-slate-200">
                  {summaryData.methodological_takeaways.map((t, idx) => (
                    <li key={idx} className="flex items-start gap-2">
                      <ArrowRight className="w-4 h-4 text-brand-600 dark:text-brand-400 shrink-0 mt-0.5" />
                      <span className="leading-relaxed">{t}</span>
                    </li>
                  ))}
                </ul>
              </div>

              <div className="p-5 rounded-2xl bg-slate-100 dark:bg-slate-950 border border-slate-200 dark:border-slate-800 space-y-3 shadow-xs">
                <h4 className="text-xs font-bold text-slate-900 dark:text-slate-100">
                  Joint Empirical Findings
                </h4>
                <ul className="space-y-2 text-xs text-slate-700 dark:text-slate-200">
                  {summaryData.joint_empirical_findings.map((f, idx) => (
                    <li key={idx} className="flex items-start gap-2">
                      <ArrowRight className="w-4 h-4 text-emerald-600 dark:text-cyan-400 shrink-0 mt-0.5" />
                      <span className="leading-relaxed">{f}</span>
                    </li>
                  ))}
                </ul>
              </div>
            </div>

            {/* Individual Structured Paper Summaries Grid */}
            <div className="space-y-3">
              <h4 className="text-xs font-bold text-slate-900 dark:text-slate-100">
                Individual Paper Breakdowns ({summaryData.paper_summaries.length})
              </h4>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                {summaryData.paper_summaries.map((p) => (
                  <div
                    key={p.document_id}
                    className="p-4 rounded-2xl bg-slate-100 dark:bg-slate-950 border border-slate-200 dark:border-slate-800 space-y-2 text-xs shadow-xs"
                  >
                    <h5 className="font-bold text-slate-900 dark:text-slate-100 line-clamp-1">
                      {p.paper_title}
                    </h5>
                    <div className="space-y-1.5 text-slate-700 dark:text-slate-300 text-xs leading-relaxed">
                      {p.objective && (
                        <p><strong className="text-slate-900 dark:text-slate-100 font-semibold">Objective:</strong> {p.objective}</p>
                      )}
                      {p.methodology && (
                        <p><strong className="text-slate-900 dark:text-slate-100 font-semibold">Method:</strong> {p.methodology}</p>
                      )}
                      {p.findings && (
                        <p><strong className="text-slate-900 dark:text-slate-100 font-semibold">Findings:</strong> {p.findings}</p>
                      )}
                      {p.limitations && (
                        <p><strong className="text-slate-900 dark:text-slate-100 font-semibold">Limitations:</strong> {p.limitations}</p>
                      )}
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </div>
        )}
      </div>

      {/* Analytics Charts: Publication Timeline & Methodology Paradigms */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Timeline Bar Chart */}
        <div className="p-6 rounded-3xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 space-y-4 shadow-xs transition-colors">
          <div className="flex items-center justify-between">
            <h3 className="text-sm font-bold text-slate-900 dark:text-slate-100 flex items-center gap-2">
              <Calendar className="w-4 h-4 text-brand-600 dark:text-brand-400" />
              <span>Publication Timeline</span>
            </h3>
            <span className="text-[11px] font-mono text-slate-500 dark:text-slate-400">Chronological (2017-2026)</span>
          </div>

          <div className="h-64 w-full">
            {data.years_distribution.length === 0 ? (
              <div className="h-full flex items-center justify-center text-xs text-slate-400">
                No publication years extracted yet.
              </div>
            ) : (
              <ResponsiveContainer width="100%" height="100%">
                <BarChart data={data.years_distribution} margin={{ top: 10, right: 10, left: -20, bottom: 0 }}>
                  <CartesianGrid strokeDasharray="3 3" stroke="#334155" opacity={0.3} />
                  <XAxis dataKey="year" stroke="#94a3b8" fontSize={11} tickLine={false} />
                  <YAxis stroke="#94a3b8" fontSize={11} tickLine={false} allowDecimals={false} />
                  <Tooltip
                    contentStyle={{
                      backgroundColor: '#020617',
                      borderColor: '#334155',
                      borderRadius: '0.75rem',
                      fontSize: '12px',
                      color: '#f8fafc',
                    }}
                    labelStyle={{ color: '#38bdf8', fontWeight: 600 }}
                  />
                  <Bar dataKey="count" fill="#10b981" radius={[6, 6, 0, 0]} name="Papers Published" />
                </BarChart>
              </ResponsiveContainer>
            )}
          </div>
        </div>

        {/* Methodology Paradigms Bar Chart (Converted from Pie Chart) */}
        <div className="p-6 rounded-3xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 space-y-4 shadow-xs transition-colors">
          <div className="flex items-center justify-between">
            <h3 className="text-sm font-bold text-slate-900 dark:text-slate-100 flex items-center gap-2">
              <Layers className="w-4 h-4 text-emerald-600 dark:text-cyan-400" />
              <span>Methodology Paradigms</span>
            </h3>
            <span className="text-[11px] font-mono text-slate-500 dark:text-slate-400">Indexed Count</span>
          </div>

          <div className="h-64 w-full">
            {data.top_methodologies.length === 0 ? (
              <div className="h-full flex items-center justify-center text-xs text-slate-400">
                No methodologies indexed yet.
              </div>
            ) : (
              <ResponsiveContainer width="100%" height="100%">
                <BarChart
                  data={data.top_methodologies}
                  layout="vertical"
                  margin={{ top: 5, right: 20, left: 20, bottom: 5 }}
                >
                  <CartesianGrid strokeDasharray="3 3" stroke="#334155" opacity={0.3} />
                  <XAxis type="number" stroke="#94a3b8" fontSize={11} tickLine={false} allowDecimals={false} />
                  <YAxis
                    type="category"
                    dataKey="name"
                    stroke="#94a3b8"
                    fontSize={10}
                    tickLine={false}
                    width={110}
                    tickFormatter={(v) => (v.length > 18 ? `${v.slice(0, 18)}...` : v)}
                  />
                  <Tooltip
                    contentStyle={{
                      backgroundColor: '#020617',
                      borderColor: '#334155',
                      borderRadius: '0.75rem',
                      fontSize: '12px',
                      color: '#f8fafc',
                    }}
                    labelStyle={{ color: '#38bdf8', fontWeight: 600 }}
                  />
                  <Bar dataKey="count" fill="#06b6d4" radius={[0, 6, 6, 0]} name="Methodology Count" />
                </BarChart>
              </ResponsiveContainer>
            )}
          </div>
        </div>
      </div>
    </div>
  );
};
